Repository ManageIQ/manageiq-content, pull requests merged in 2018-09, with the labels that each got.

#413 Updated requested method to fix vm_reconfigure via rest-api.
  content/automate/ManageIQ/System/CommonMethods/QuotaMethods.class/__methods__/requested.rb
  spec/automation/unit/method_validation/requested_spec.rb
Labels: bug

#422 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#424 [GAPRINDASHVILI] Correct require_domain_file statement
  spec/content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/restorevmattributes_spec.rb
Labels: test

#423 Adding log_and_notify method into log_object embedded method.
  content/automate/ManageIQ/System/CommonMethods/Utils.class/__methods__/log_object.rb
  spec/content/automate/ManageIQ/System/CommonMethods/Utils.class/__methods__/log_object_spec.rb
Labels: enhancement

#420 Add storage profile support in vmware_best_fit_least_utilized method.
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/vmware_best_fit_least_utilized.rb
  spec/automation/unit/method_validation/vmware_best_fit_least_utilized_spec.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/vmware_best_fit_least_utilized_spec.rb
Labels: blocker, bug, gaprindashvili/yes, providers/provisioning, providers/virtual

#428 Remove Gemnasium badge from README.md since it was discontinued
  README.md
Labels: documentation

#427 Use embedded log method.
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/vmware_best_fit_least_utilized.rb
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/vmware_best_fit_least_utilized.yaml
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/vmware_best_fit_least_utilized_spec.rb
Labels: enhancement, gaprindashvili/no, providers/provisioning, providers/virtual

#431 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation

#421 Refactor and add specs for Transformation Hosts Common Utils
  content/automate/ManageIQ/Transformation/Infrastructure/VM/vmwarews.class/__methods__/utils.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/Common.class/__methods__/utils.rb
  spec/content/automate/ManageIQ/Transformation/TransformationHosts/Common.class/__methods__/utils_spec.rb
Labels: blocker, enhancement, gaprindashvili/yes, technical debt, test, transformation

#434 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation

#417 Add support to apply right-size recommendation during transformation
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/applyrightsize.rb
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/applyrightsize.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/__class__.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/posttransform.yaml
  spec/content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/applyrightsize_spec.rb
Labels: blocker, enhancement, gaprindashvili/yes, hammer/yes, transformation
