Repository ManageIQ/manageiq-content, pull requests merged in 2018-05, with the labels that each got.

#283 Move the task message into check for task presence
  content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirement.class/__methods__/update_service_retirement_status.rb
Labels: bug

#281 Change check for start_retirement to not initialized vs retiring
  content/automate/ManageIQ/Cloud/Orchestration/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  spec/automation/unit/method_validation/orchestration_retirement_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/start_retirement_spec.rb
Labels: enhancement

#287 [GAPRINDASHVILI] [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#289 [Changelog] Update for Sprint 85
  CHANGELOG.md
Labels: documentation

#296 Fix servicetemplateprovisionrequest_denied approver_href method.
  content/automate/ManageIQ/Service/Provisioning/Email.class/__methods__/servicetemplateprovisionrequest_denied.rb
Labels: bug

#299 Created new namespace for Configuration/Email.
  content/automate/ManageIQ/Configuration/Email.class/__class__.yaml
  content/automate/ManageIQ/Configuration/Email.class/default.yaml
  content/automate/ManageIQ/Configuration/__namespace__.yaml
Labels: enhancement

#302 Email instances for Cloud VM provisioning.
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/VMProvision_VM.class/__class__.yaml
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/VMProvision_VM.class/clone_to_vm.yaml
  content/automate/ManageIQ/System/Notification/Email.class/__methods__/miq_provision_customize_body.rb
  content/automate/ManageIQ/System/Notification/Email.class/__methods__/miq_provision_customize_body.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisioncomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisionrequestapproverapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisionrequestapproverdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisionrequestapproverpending.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisionrequestrequesterapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisionrequestrequesterdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisionrequestrequesterpending.yaml
  content/automate/ManageIQ/System/Policy.class/miqprovisionrequest_approved.yaml
  content/automate/ManageIQ/System/Policy.class/miqprovisionrequest_denied.yaml
  content/automate/ManageIQ/System/Policy.class/miqprovisionrequest_pending.yaml
  spec/content/automate/ManageIQ/System/Notification/Email.class/__methods__/miq_provision_customize_body_spec.rb
Labels: enhancement

#303 Email instances for Infra VM provisioning.
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/VMProvision_Template.class/__class__.yaml
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/VMProvision_VM.class/__class__.yaml
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/VMProvision_VM.class/clone_to_vm.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisioncomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestapproverapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestapproverdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestapproverpending.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestrequesterapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestrequesterdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestrequesterpending.yaml
Labels: enhancement

#304 Email instances for Cloud and Infrastructure retirement.
  content/automate/ManageIQ/System/Event/MiqEvent/POLICY.class/vm_retire_warn.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudorchestrationvmenteredretirement.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudorchestrationvmretired.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudorchestrationvmretirewarn.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudvmenteredretirement.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudvmretired.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudvmretireextend.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudvmretirewarn.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructurevmenteredretirement.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructurevmretired.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructurevmretireextend.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructurevmretirewarn.yaml
  content/automate/ManageIQ/System/Request.class/vm_retire_extend.yaml
Labels: enhancement

#305 Updated Email instances for Infra VM provisioning.
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisioncomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestapproverapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestapproverdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestapproverpending.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestrequesterapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestrequesterdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestrequesterpending.yaml
Labels: enhancement

#306 Updated Email instances for Cloud VM provisioning.
  content/automate/ManageIQ/System/Notification/Email.class/__methods__/miq_provision_customize_body.rb
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisioncomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisionrequestapproverapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisionrequestapproverdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisionrequestapproverpending.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisionrequestrequesterapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisionrequestrequesterdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisionrequestrequesterpending.yaml
Labels: enhancement

#307 Updated existing V2v instances in Configuration/Email.
  content/automate/ManageIQ/System/Notification/Email.class/transformationplanrequestapproverapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/transformationplanrequestapproverdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/transformationplanrequestapproverpending.yaml
  content/automate/ManageIQ/System/Notification/Email.class/transformationplanrequestrequesterapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/transformationplanrequestrequesterdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/transformationplanrequestrequesterpending.yaml
Labels: enhancement

#298 Bump to ruby 2.4.4 for great justice
  .travis.yml
Labels: test

#312 Fix System/CommonMethods/MiqAe directory name
  content/automate/ManageIQ/System/CommonMethods/MiqAe.class/__class__.yaml
  content/automate/ManageIQ/System/CommonMethods/MiqAe.class/__methods__/weighted_update_status.rb
  content/automate/ManageIQ/System/CommonMethods/MiqAe.class/__methods__/weighted_update_status.yaml
Labels: bug
