Repository ManageIQ/manageiq-content, pull requests merged in 2018-08, with the labels that each got.

#382 Fix default cleanup state machine
  content/automate/ManageIQ/System/CommonMethods/MiqAe.class/__methods__/weightedupdatestatus.rb
  content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformationcleanup.rb
  content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformationcleanup.yaml
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/checkpoweredon.rb
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/checkpoweredon.yaml
  content/automate/ManageIQ/Transformation/Infrastructure/VM/rhevm.class/__methods__/checkpoweredon.rb
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/posttransform.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformationcleanup.yaml
Labels: blocker, bug, gaprindashvili/yes, transformation

#366 Added vm_retire_extend method for new email.
  content/automate/ManageIQ/System/Request.class/__methods__/vm_retire_extend.rb
  content/automate/ManageIQ/System/Request.class/__methods__/vm_retire_extend.yaml
  content/automate/ManageIQ/System/Request.class/vm_retire_extend.yaml
  spec/content/automate/ManageIQ/System/Request.class/__methods__/vm_retire_extend_spec.rb
Labels: bug

#388 Fix quota requested cloud_volume calculations.
  content/automate/ManageIQ/System/CommonMethods/QuotaMethods.class/__methods__/requested.rb
  spec/automation/unit/method_validation/calculate_requested_spec.rb
Labels: bug

#389 Rename quota requested spec.
  spec/automation/unit/method_validation/requested_spec.rb
Labels: cleanup

#393 Transformation - Fix virt-v2v success check
  content/automate/ManageIQ/Transformation/TransformationHosts/Common.class/__methods__/vmchecktransformed.rb
Labels: blocker, bug, gaprindashvili/yes, transformation

#392 Fix cleanup state machine path build
  content/automate/ManageIQ/System/CommonMethods/MiqAe.class/__methods__/weightedupdatestatus.rb
Labels: blocker, bug, gaprindashvili/yes, transformation

#375 Changed validate_quota method to check individual quota items.
  content/automate/ManageIQ/System/CommonMethods/QuotaMethods.class/__methods__/validate_quota.rb
  spec/automation/unit/method_validation/validate_quota_spec.rb
Labels: bug

#395 Remove check on number of runners when converting VM
  content/automate/ManageIQ/Transformation/TransformationHosts/Common.class/__methods__/vmtransform.rb
Labels: blocker, bug, gaprindashvili/yes, transformation

#373 Removed 7 ConfigurationManagement specs.
  spec/automation/unit/method_validation/ansible_tower_check_provisioned_spec.rb
  spec/automation/unit/method_validation/ansible_tower_preprovision_spec.rb
  spec/automation/unit/method_validation/ansible_tower_provision_spec.rb
  spec/automation/unit/method_validation/launch_ansible_job_spec.rb
  spec/automation/unit/method_validation/wait_for_completion_spec.rb
  spec/automation/unit/method_validation/wait_for_ip_spec.rb
  spec/content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/update_serviceprovision_status_spec.rb
Labels: technical debt

#397 Restore VM ownership and retirement when migrating
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/restorevmattributes.rb
  spec/content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/restorevmattributes_spec.rb
Labels: blocker, enhancement, gaprindashvili/yes, transformation

#401 Add Openstack volume.update.end event handler
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/volume.update.end.yaml
Labels: bug, events, providers/cloud

#399 Refactor and add specs for Transformation - CheckVMInInventory
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/checkvmininventory.rb
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/checkvmininventory.yaml
  content/automate/ManageIQ/Transformation/Infrastructure/VM/rhevm.class/__methods__/checkvmininventory.rb
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transform.yaml
  spec/content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/checkvmininventory_spec.rb
Labels: enhancement, gaprindashvili/yes, test, transformation

#371 Event handling for Openstack keypair events
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/keypair.create.end.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/keypair.delete.end.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/keypair.update.end.yaml
Labels: bug, events, providers/cloud

#372 Add event handling for Openstack port events
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/port.create.end.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/port.delete.end.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/port.update.end.yaml
Labels: bug, events, providers/cloud

#402 Add state_machine_phase attribute to transformation state machines
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/__class__.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformation.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformationcleanup.yaml
Labels: blocker, enhancement, gaprindashvili/yes, transformation

#400 Fixed files in wrong namespace.
  content/automate/ManageIQ/Cloud/Orchestration/Operations/Methods.class/__methods__/available_vdc_networks.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/tagasdisabled.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/tagasenabled.rb
  spec/content/automate/ManageIQ/Cloud/Orchestration/Operations/Methods.class/__methods__/available_vdc_networks_spec.rb
Labels: bug, cleanup

#386 Adding Inspectme functionality into log_object embedded method.
  content/automate/ManageIQ/System/CommonMethods/Utils.class/__methods__/log_object.rb
  spec/content/automate/ManageIQ/System/CommonMethods/Utils.class/__methods__/log_object_spec.rb
Labels: enhancement

#404 Prevent AR validation failure
  spec/automation/unit/method_validation/dialog_parser_spec.rb
Labels: bug, gaprindashvili/yes, test

#405 Change VMware URI to connect directly to ESXi
  content/automate/ManageIQ/Transformation/Infrastructure/VM/vmwarews.class/__methods__/utils.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/Common.class/__methods__/utils.rb
Labels: blocker, enhancement, gaprindashvili/yes, transformation

#391 Transformation - Refactor task and vm collection
  content/automate/ManageIQ/Transformation/Common.class/__methods__/utils.rb
  content/automate/ManageIQ/Transformation/Common.class/__methods__/utils.yaml
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/utils_spec.rb
Labels: enhancement, gaprindashvili/yes, technical debt, test, transformation

#407 Escape username of VMware host
  content/automate/ManageIQ/Transformation/TransformationHosts/Common.class/__methods__/utils.rb
Labels: blocker, bug, gaprindashvili/yes, transformation

#374 Removed ConfigurationManagement namespace.
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Operations/JobTemplate.class/__class__.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Operations/JobTemplate.class/_missing.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Operations/StateMachines/Job.class/__class__.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Operations/StateMachines/Job.class/__methods__/launch_ansible_job.rb
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Operations/StateMachines/Job.class/__methods__/launch_ansible_job.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Operations/StateMachines/Job.class/__methods__/wait_for_completion.rb
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Operations/StateMachines/Job.class/__methods__/wait_for_completion.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Operations/StateMachines/Job.class/__methods__/wait_for_ip.rb
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Operations/StateMachines/Job.class/__methods__/wait_for_ip.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Operations/StateMachines/Job.class/default.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Operations/StateMachines/__namespace__.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Operations/__namespace__.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/Email.class/__class__.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/Email.class/__methods__/serviceprovision_complete.rb
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/Email.class/__methods__/serviceprovision_complete.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/Email.class/__methods__/servicetemplateprovisionrequest_approved.rb
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/Email.class/__methods__/servicetemplateprovisionrequest_approved.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/Email.class/serviceprovision_complete.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/Email.class/servicetemplateprovisionrequest_approved.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__class__.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/check_provisioned.rb
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/check_provisioned.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/post_provision.rb
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/post_provision.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/preprovision.rb
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/preprovision.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/provision.rb
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/provision.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/update_serviceprovision_status.rb
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/update_serviceprovision_status.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/_missing.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/catalogiteminitialization.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/StateMachines/__namespace__.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/Provisioning/__namespace__.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/Service/__namespace__.yaml
  content/automate/ManageIQ/ConfigurationManagement/AnsibleTower/__namespace__.yaml
  content/automate/ManageIQ/ConfigurationManagement/__namespace__.yaml
Labels: technical debt

#409 Trigger Nuage targeted refresh more often
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_subnettemplate_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_zone_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_zonetemplate_delete.yaml
Labels: enhancement, events, providers/network

#406 Prepare Nuage authentication attributes (for Embedded Ansible)
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/__class__.yaml
Labels: enhancement, events, providers/network

#410 Do not check instance variables in specs for Transformation - Common - Utils
  content/automate/ManageIQ/Transformation/Common.class/__methods__/utils.rb
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/utils_spec.rb
Labels: blocker, bug, gaprindashvili/yes, transformation

#408 Refactor and add specs for Transformation - AssessTransformation
  content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformation.rb
  content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformation.yaml
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformation_spec.rb
Labels: blocker, gaprindashvili/yes, refactoring, technical debt, transformation

#398 Add CustomButtonEvent to automate explorer
  content/automate/ManageIQ/System/Event/CustomButtonEvent/UI.class/__class__.yaml
  content/automate/ManageIQ/System/Event/CustomButtonEvent/UI.class/button.trigger.start.yaml
  content/automate/ManageIQ/System/Event/CustomButtonEvent/__namespace__.yaml
Labels: enhancement, events

#411 Add plugin display name
  lib/manageiq/content/engine.rb
Labels: enhancement

#412 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-5
  CHANGELOG.md
Labels: documentation

#414 Added log_and_exit utility method
  content/automate/ManageIQ/System/CommonMethods/Utils.class/__methods__/log_object.rb
  spec/content/automate/ManageIQ/System/CommonMethods/Utils.class/__methods__/log_object_spec.rb
Labels: enhancement

#415 [Changelog] Update for Sprint 93
  CHANGELOG.md
Labels: documentation

#416 Adding log and raise error method into log_object embedded method.
  content/automate/ManageIQ/System/CommonMethods/Utils.class/__methods__/log_object.rb
  spec/content/automate/ManageIQ/System/CommonMethods/Utils.class/__methods__/log_object_spec.rb
Labels: enhancement
