Repository ManageIQ/manageiq-content, pull requests merged in 2018-03, with the labels that each got.

#256 [FINE] Remove the options hash which is new in version 5.9.
  content/automate/ManageIQ/System/Event/StateMachines/Refresh.class/__methods__/check_refreshed.yaml
  content/automate/ManageIQ/System/Event/StateMachines/Refresh.class/__methods__/target_refresh.yaml
Labels: bug

#263 [Changelog] Update for Sprint 81
  CHANGELOG.md
Labels: documentation

#261 Add Azure events for targeted refresh
  content/automate/ManageIQ/System/Event/EmsEvent/Azure.class/images_delete_endrequest.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/Azure.class/loadbalancers_delete_endrequest.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/Azure.class/locks_delete_endrequest.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/Azure.class/locks_write_endrequest.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/Azure.class/networksecuritygroups_delete_endrequest.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/Azure.class/networksecuritygroups_securityrules_endrequest.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/Azure.class/publicipaddresses_delete_endrequest.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/Azure.class/virtualmachines_generalize_endrequest.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/Azure.class/virtualnetworks_delete_endrequest.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/Azure.class/virtualnetworks_subnets_endrequest.yaml
Labels: enhancement

#252 Add VM Transformation state machine
  content/automate/ManageIQ/System/CommonMethods/MiqAe/__class__.yaml
  content/automate/ManageIQ/System/CommonMethods/MiqAe/__methods__/weighted_update_status.rb
  content/automate/ManageIQ/System/CommonMethods/MiqAe/__methods__/weighted_update_status.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/__class__.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformation.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/vmwarews2rhevm_vddk.yaml
Labels: enhancement, transformation

#265 Modify on_{entry,exit,error} path to use WeightedUpdateStatus
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformation.yaml
Labels: bug, transformation

#267 [Changelog] Update for Sprint 82
  CHANGELOG.md
Labels: documentation

#268 use 2.3.6 on travis
  .travis.yml
Labels: test

#255 Updated spec dialog parser
  content/automate/ManageIQ/Service/Provisioning/StateMachines/Methods.class/__methods__/dialog_parser.rb
  spec/automation/unit/method_validation/dialog_parser_spec.rb
Labels: enhancement, gaprindashvili/yes

#270 [FINE] use 2.3.6 on travis
  .travis.yml
Labels: test

#269 [GAPRINDASHVILI] use 2.3.6 on travis
  .travis.yml
Labels: test
