Repository ManageIQ/manageiq-content, pull requests merged in 2018-11, with the labels that each got.

#353 Refactoring cloud vm provisioning placement best fit methods
  content/automate/ManageIQ/Cloud/VM/Provisioning/Placement.class/__methods__/best_fit_azure.rb
  content/automate/ManageIQ/Cloud/VM/Provisioning/Placement.class/__methods__/best_fit_google.rb
  content/automate/ManageIQ/Cloud/VM/Provisioning/Placement.class/__methods__/best_fit_openstack.rb
  spec/content/automate/ManageIQ/Cloud/VM/Provisioning/Placement.class/__methods__/best_fit_amazon_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Provisioning/Placement.class/__methods__/best_fit_azure_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Provisioning/Placement.class/__methods__/best_fit_google_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Provisioning/Placement.class/__methods__/best_fit_openstack_spec.rb
Labels: refactoring

#464 Modified update_status in Generic Lifecycle to use embedded methods.
  content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/update_status.rb
  content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/update_status.yaml
  spec/content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/update_status_spec.rb
Labels: refactoring

#455 Deny request if no conversion host is configured
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__class__.yaml
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__/deny_request.rb
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__/deny_request.yaml
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__/pending_request.rb
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__/validate_request.rb
Labels: blocker, enhancement, hammer/yes, transformation

#457 Use task cancelation_status to trigger cancelation
  content/automate/ManageIQ/System/CommonMethods/MiqAe.class/__methods__/weightedupdatestatus.rb
  content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformation.rb
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformation_spec.rb
Labels: blocker, enhancement, hammer/yes, transformation

#462 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-6
  CHANGELOG.md
Labels: documentation

#460 Modified Finish method in Generic Lifecycle to use embedded methods.
  content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/finish.rb
  content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/finish.yaml
  spec/content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/finish_spec.rb
Labels: refactoring

#450 Modified Start method in Generic Lifecycle to use embedded methods.
  content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/start.rb
  content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/start.yaml
  spec/content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/start_spec.rb
Labels: refactoring

#465 [Changelog] Update for Sprint 98, G-6, and H-B2
  CHANGELOG.md
Labels: documentation

#467 Modified vm_retire_extend in System Request to use embedded methods.
  content/automate/ManageIQ/System/Request.class/__methods__/vm_retire_extend.rb
  content/automate/ManageIQ/System/Request.class/__methods__/vm_retire_extend.yaml
  spec/content/automate/ManageIQ/System/Request.class/__methods__/vm_retire_extend_spec.rb
Labels: refactoring

#466 Modified check_completed in Generic Lifecycle to use embedded methods.
  content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/check_completed.rb
  content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/check_completed.yaml
  spec/content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/check_completed_spec.rb
Labels: refactoring

#469 Fix travis failure.
  spec/automation/unit/method_validation/azure_auto_placement_spec.rb
  spec/automation/unit/method_validation/google_auto_placement_spec.rb
Labels: test

#468 [HAMMER] [Changelog] Update for Hammer RC-1
  CHANGELOG.md
Labels: documentation

#461 Modified requested method for reconfigure disk_remove.
  content/automate/ManageIQ/System/CommonMethods/QuotaMethods.class/__methods__/requested.rb
  spec/automation/unit/method_validation/requested_spec.rb
Labels: bug

#473 Fix TransformationPlanRequest approval - Set message
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__/deny_request.rb
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__/validate_request.rb
Labels: blocker, bug, hammer/yes, transformation

#449 Modified InspectMe method to use embedded log_object methods.
  content/automate/ManageIQ/System/Request.class/__methods__/inspectme.rb
  content/automate/ManageIQ/System/Request.class/__methods__/inspectme.yaml
  spec/automation/unit/method_validation/inspect_me_spec.rb
  spec/content/automate/ManageIQ/System/Request.class/__methods__/inspectme_spec.rb
Labels: refactoring

#474 Changed disk_name to symbol in requested Quota method.
  content/automate/ManageIQ/System/CommonMethods/QuotaMethods.class/__methods__/requested.rb
  spec/automation/unit/method_validation/requested_spec.rb
Labels: blocker, bug, fine/yes, gaprindashvili/yes, hammer/yes

#472 Disconnect storage when disconnecting a VM
  content/automate/ManageIQ/System/Event/EmsEvent/EVM.class/destroyvm_task_complete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/user_remove_vm_finished.yaml
Labels: blocker, bug, events, gaprindashvili/yes, hammer/yes, providers/virtual

#477 [HAMMER] [Changelog] Update for Hammer RC2
  CHANGELOG.md
Labels: documentation
