Repository ManageIQ/manageiq-content, pull requests merged in 2018-07, with the labels that each got.

#330 Refactoring cloud vm retirement approve_request method
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/approve_request.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/approve_request_spec.rb
Labels: refactoring

#332 Remove references to host provisioning
  content/automate/ManageIQ/Infrastructure/Host/Lifecycle.class/__class__.yaml
  content/automate/ManageIQ/Infrastructure/Host/Lifecycle.class/provisioning.yaml
  content/automate/ManageIQ/Infrastructure/Host/Lifecycle.class/retirement.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/Email.class/__class__.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/Email.class/__methods__/miqhostprovision_complete.rb
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/Email.class/__methods__/miqhostprovision_complete.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/Email.class/__methods__/miqhostprovisionrequest_approved.rb
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/Email.class/__methods__/miqhostprovisionrequest_approved.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/Email.class/miqhostprovision_complete.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/Email.class/miqhostprovisionrequest_approved.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/Profile.class/__class__.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/Profile.class/__methods__/get_deploy_dialog.rb
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/Profile.class/__methods__/get_deploy_dialog.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/Profile.class/_missing.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/Profile.class/evmgroup-super_administrator.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/HostProvision.class/__class__.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/HostProvision.class/__methods__/update_provision_status.rb
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/HostProvision.class/__methods__/update_provision_status.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/HostProvision.class/host_pxe_install.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/__class__.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/__methods__/check_provisioned.rb
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/__methods__/check_provisioned.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/__methods__/customizerequest.rb
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/__methods__/customizerequest.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/__methods__/postprovision_host.rb
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/__methods__/postprovision_host.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/__methods__/preprovision_host.rb
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/__methods__/preprovision_host.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/__methods__/provision.rb
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/__methods__/provision.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/checkprovisioned.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/customizerequest.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/postprovision_host.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/preprovision_host.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/Methods.class/provision.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/__namespace__.yaml
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/__namespace__.yaml
  content/automate/ManageIQ/System/CommonMethods/StateMachineMethods.class/host_provision_finished.yaml
  content/automate/ManageIQ/System/Notification/Email.class/miqhostprovisioncomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/miqhostprovisionrequestapproved.yaml
  content/automate/ManageIQ/System/Policy.class/__methods__/miqhostprovision_auto_approve.rb
  content/automate/ManageIQ/System/Policy.class/__methods__/miqhostprovision_auto_approve.yaml
  content/automate/ManageIQ/System/Policy.class/miqhostprovisionrequest_approved.yaml
  content/automate/ManageIQ/System/Policy.class/miqhostprovisionrequest_created.yaml
  content/automate/ManageIQ/System/Policy.class/miqhostprovisionrequest_starting.yaml
  content/automate/ManageIQ/System/Policy.class/miqhostprovisionrequest_updated.yaml
  content/automate/ManageIQ/System/Request.class/ui_host_provision_info.yaml
  spec/automation/unit/builtin_method_validation/parse_automation_request_spec.rb
  spec/automation/unit/builtin_method_validation/parse_provider_category_spec.rb
Labels: gaprindashvili/no, technical debt

#352 [Changelog] Update for Sprint 89
  CHANGELOG.md
Labels: documentation

#346 Deprecate old Cloud Vm Provisioning email methods
  content/automate/ManageIQ/Cloud/VM/Provisioning/Email.class/__methods__/miqprovision_complete.rb
  content/automate/ManageIQ/Cloud/VM/Provisioning/Email.class/__methods__/miqprovisionrequest_approved.rb
  content/automate/ManageIQ/Cloud/VM/Provisioning/Email.class/__methods__/miqprovisionrequest_denied.rb
  content/automate/ManageIQ/Cloud/VM/Provisioning/Email.class/__methods__/miqprovisionrequest_pending.rb
Labels: technical debt

#345 Deprecate old Cloud Orchestration Retirement email method.
  content/automate/ManageIQ/Cloud/Orchestration/Retirement/Email.class/__methods__/stack_retirement_emails.rb
Labels: technical debt

#343 Deprecate old Cloud Orchestration Provisioning email methods.
  content/automate/ManageIQ/Cloud/Orchestration/Provisioning/Email.class/__methods__/serviceprovision_complete.rb
  content/automate/ManageIQ/Cloud/Orchestration/Provisioning/Email.class/__methods__/servicetemplateprovisionrequest_approved.rb
Labels: technical debt

#342 Deprecate old AutomationManagement email methods.
  content/automate/ManageIQ/AutomationManagement/AnsibleTower/Service/Provisioning/Email.class/__methods__/serviceprovision_complete.rb
  content/automate/ManageIQ/AutomationManagement/AnsibleTower/Service/Provisioning/Email.class/__methods__/servicetemplateprovisionrequest_approved.rb
Labels: technical debt

#284 Add checks for retirement of correct child service in bundle
  content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/check_service_retired.rb
  spec/content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/check_service_retired_spec.rb
Labels: enhancement

#325 Refactoring cloud vm retirement amazon_check_pre_retirement method
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/amazon_check_pre_retirement.rb
  spec/automation/unit/method_validation/amazon_check_pre_retirement_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/amazon_check_pre_retirement_spec.rb
Labels: refactoring

#356 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-4
  CHANGELOG.md
Labels: documentation

#354 Refactoring cloud vm provisioning profile methods
  content/automate/ManageIQ/Cloud/VM/Provisioning/Profile.class/__methods__/get_deploy_dialog.rb
  content/automate/ManageIQ/Cloud/VM/Provisioning/Profile.class/__methods__/vm_dialog_name_prefix.rb
  spec/content/automate/ManageIQ/Cloud/VM/Provisioning/Profile.class/__methods__/get_deploy_dialog_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Provisioning/Profile.class/__methods__/vm_dialog_name_prefix_spec.rb
Labels: refactoring

#349 Deprecate old email methods.
  content/automate/ManageIQ/Cloud/VM/Retirement/Email.class/__methods__/vm_retire_extend.rb
  content/automate/ManageIQ/Cloud/VM/Retirement/Email.class/__methods__/vm_retirement_emails.rb
  content/automate/ManageIQ/Infrastructure/Configured_System/Provisioning/Email.class/__methods__/provision_complete.rb
  content/automate/ManageIQ/Infrastructure/Configured_System/Provisioning/Email.class/__methods__/request_approved.rb
  content/automate/ManageIQ/Infrastructure/VM/Migrate/Email.class/__methods__/vmmigraterequest_approved.rb
  content/automate/ManageIQ/Infrastructure/VM/Migrate/Email.class/__methods__/vmmigratetask_complete.rb
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/Email.class/__methods__/miqprovision_complete.rb
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/Email.class/__methods__/miqprovisionrequest_approved.rb
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/Email.class/__methods__/miqprovisionrequest_denied.rb
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/Email.class/__methods__/miqprovisionrequest_pending.rb
  content/automate/ManageIQ/Infrastructure/VM/Reconfigure/Email.class/__methods__/vmreconfigure_request_approved.rb
  content/automate/ManageIQ/Infrastructure/VM/Reconfigure/Email.class/__methods__/vmreconfigure_task_complete.rb
  content/automate/ManageIQ/Infrastructure/VM/Retirement/Email.class/__methods__/vm_retire_extend.rb
  content/automate/ManageIQ/Infrastructure/VM/Retirement/Email.class/__methods__/vm_retirement_emails.rb
  content/automate/ManageIQ/Service/Provisioning/Email.class/__methods__/serviceprovision_complete.rb
  content/automate/ManageIQ/Service/Provisioning/Email.class/__methods__/servicetemplateprovisionrequest_approved.rb
  content/automate/ManageIQ/Service/Provisioning/Email.class/__methods__/servicetemplateprovisionrequest_denied.rb
  content/automate/ManageIQ/Service/Provisioning/Email.class/__methods__/servicetemplateprovisionrequest_pending.rb
  content/automate/ManageIQ/Service/Provisioning/Email.class/__methods__/servicetemplateprovisionrequest_warning.rb
Labels: technical debt

#361 Changed ansible_tower_job instance to use AutomationManagement namespace.
  content/automate/ManageIQ/System/Request.class/ansible_tower_job.yaml
Labels: refactoring

#351 Add support for MAC address in network mapping
  content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformation.rb
Labels: blocker, enhancement, gaprindashvili/yes, transformation

#358 Fix computation of currently running conversions by host
  content/automate/ManageIQ/Transformation/TransformationHosts/Common.class/__methods__/utils.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/vmtransform_vmwarews2rhevm_vddk.rb
Labels: blocker, bug, gaprindashvili/yes, transformation

#363 Adjust Automate Instance names to new event type prefix
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_domain_create.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_domain_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_domain_update.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_enterprise_create.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_enterprise_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_enterprise_update.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_policygroup_create.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_policygroup_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_policygroup_update.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_subnet_create.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_subnet_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_subnet_update.yaml
Labels: enhancement, events, providers/network

#365 Actually rename AE Instances, not just fixture filename
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_domain_create.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_domain_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_domain_update.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_enterprise_create.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_enterprise_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_enterprise_update.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_policygroup_create.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_policygroup_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_policygroup_update.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_subnet_create.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_subnet_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_subnet_update.yaml
Labels: enhancement, events, providers/network

#355 Add support for pre/post-migration playbook
  content/automate/ManageIQ/Transformation/Ansible.class/__class__.yaml
  content/automate/ManageIQ/Transformation/Ansible.class/__methods__/checkplaybookasaservice.rb
  content/automate/ManageIQ/Transformation/Ansible.class/__methods__/checkplaybookasaservice.yaml
  content/automate/ManageIQ/Transformation/Ansible.class/__methods__/launchplaybookasaservice.rb
  content/automate/ManageIQ/Transformation/Ansible.class/__methods__/launchplaybookasaservice.yaml
  content/automate/ManageIQ/Transformation/Ansible.class/_missing.yaml
  content/automate/ManageIQ/Transformation/Infrastructure/VM/rhevm.class/__methods__/checkpoweredon.rb
  content/automate/ManageIQ/Transformation/Infrastructure/VM/rhevm.class/__methods__/checkpoweredon.yaml
  content/automate/ManageIQ/Transformation/StateMachines/Ansible.class/__class__.yaml
  content/automate/ManageIQ/Transformation/StateMachines/Ansible.class/transformationplaybook.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformation.yaml
Labels: blocker, enhancement, gaprindashvili/yes, transformation

#364 [Changelog] Update for Sprint 90
  CHANGELOG.md
Labels: documentation

#357 Update WeightedUpdateStatus to handle task cancellation and cleanup
  content/automate/ManageIQ/System/CommonMethods/MiqAe.class/__methods__/weightedupdatestatus.rb
Labels: enhancement, gaprindashvili/yes, transformation

#367 Trigger targeted refresh for new Nuage entities
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_floatingip_create.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_floatingip_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_floatingip_update.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_l2domain_create.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_l2domain_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_l2domain_update.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_sharednetworkresource_create.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_sharednetworkresource_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_sharednetworkresource_update.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_vport_create.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_vport_delete.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/NUAGE.class/nuage_vport_update.yaml
Labels: enhancement, events, providers/network

#368 Add event handling for Openstack volume attachment events
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/compute.instance.volume.attach.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/compute.instance.volume.detach.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/volume.attach.end.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/volume.detach.end.yaml
Labels: bug, events, providers/cloud

#369 Refactor set retry for pre/post migration playbooks
  content/automate/ManageIQ/Transformation/Ansible.class/__methods__/checkplaybookasaservice.rb
Labels: blocker, enhancement, gaprindashvili/yes, transformation

#370 Fix hook string passing for pre/post-migration playbooks
  content/automate/ManageIQ/Transformation/StateMachines/Ansible.class/transformationplaybook.yaml
Labels: blocker, bug, gaprindashvili/yes, transformation

#376 Spell resource right
  content/automate/ManageIQ/Cloud/Orchestration/Operations/Methods.class/__methods__/available_resource_groups.rb
  spec/content/automate/ManageIQ/Cloud/Orchestration/Operations/Methods.class/__methods__/available_resource_groups_spec.rb
Labels: cleanup

#380 Allow running playbook against powered off VM
  content/automate/ManageIQ/Transformation/Ansible.class/__methods__/launchplaybookasaservice.rb
Labels: blocker, enhancement, gaprindashvili/yes, transformation

#379 Fix transformation host selection
  content/automate/ManageIQ/Transformation/TransformationHosts/Common.class/__methods__/utils.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/Common.class/__methods__/vmtransform.rb
Labels: blocker, bug, gaprindashvili/yes, transformation

#381 Use targeted refresh during transformation
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/vm_import_from_configuration_executed_successfully.yaml
  content/automate/ManageIQ/Transformation/Infrastructure/VM/rhevm.class/__methods__/checkvmininventory.rb
Labels: blocker, enhancement, gaprindashvili/yes, transformation

#377 Fix weightedupdatestatus for cancellation
  content/automate/ManageIQ/System/CommonMethods/MiqAe.class/__methods__/weightedupdatestatus.rb
Labels: blocker, bug, gaprindashvili/yes, transformation

#378 Add default cleanup state machine for VM transformation
  content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformationcleanup.rb
  content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformationcleanup.yaml
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/poweron.rb
  content/automate/ManageIQ/Transformation/Infrastructure/VM/rhevm.class/__methods__/checkpoweredon.rb
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/__class__.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformation.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformationcleanup.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/Common.class/__methods__/killvirtv2v.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/Common.class/__methods__/killvirtv2v.yaml
Labels: blocker, enhancement, gaprindashvili/yes, transformation

#384 Options hash should not store Active Record objects
  spec/automation/unit/method_validation/filter_by_dialog_parameters_spec.rb
Labels: technical debt, test
