Repository ManageIQ/manageiq-content, pull requests merged in 2018-04, with the labels that each got.

#272 Add changes for service, vm retire request approval
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/RetirementRequestApproval.class/__class__.yaml
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/approve_request.rb
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/approve_request.yaml
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/pending_request.rb
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/pending_request.yaml
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/validate_request.rb
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/validate_request.yaml
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/RetirementRequestApproval.class/default.yaml
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/RetirementRequestApproval.class/__class__.yaml
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/approve_request.rb
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/approve_request.yaml
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/pending_request.rb
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/pending_request.yaml
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/validate_request.rb
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/validate_request.yaml
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/RetirementRequestApproval.class/default.yaml
  content/automate/ManageIQ/Service/Lifecycle.class/retirement.yaml
  content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirementRequestApproval.class/__class__.yaml
  content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirementRequestApproval.class/__methods__/approve_request.rb
  content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirementRequestApproval.class/__methods__/approve_request.yaml
  content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirementRequestApproval.class/__methods__/pending_request.rb
  content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirementRequestApproval.class/__methods__/pending_request.yaml
  content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirementRequestApproval.class/__methods__/validate_request.rb
  content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirementRequestApproval.class/__methods__/validate_request.yaml
  content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirementRequestApproval.class/default.yaml
  content/automate/ManageIQ/System/Policy.class/serviceretirerequest_created.yaml
  content/automate/ManageIQ/System/Policy.class/vmretirerequest_created.yaml
  content/automate/ManageIQ/System/Policy.class/vmretirerequest_starting.yaml
Labels: enhancement

#276 Fix ManageIQ/manageiq-content/issues/275
  content/automate/ManageIQ/Transformation/TransformationHosts/StateMachines/TransformationHostRole.class/disable.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/StateMachines/TransformationHostRole.class/enable.yaml
Labels: bug, gaprindashvili/yes, transformation

#254 Add in the miq. automate and vmdb roles
  content/ansible/roles/manageiq-core.manageiq-automate/LICENSE
  content/ansible/roles/manageiq-core.manageiq-automate/README.md
  content/ansible/roles/manageiq-core.manageiq-automate/action_plugins/manageiq_automate.py
  content/ansible/roles/manageiq-core.manageiq-automate/defaults/main.yml
  content/ansible/roles/manageiq-core.manageiq-automate/examples/.gitkeep
  content/ansible/roles/manageiq-core.manageiq-automate/handlers/main.yml
  content/ansible/roles/manageiq-core.manageiq-automate/library/manageiq_automate.py
  content/ansible/roles/manageiq-core.manageiq-automate/meta/main.yml
  content/ansible/roles/manageiq-core.manageiq-automate/tasks/main.yml
  content/ansible/roles/manageiq-core.manageiq-automate/tests/inventory
  content/ansible/roles/manageiq-core.manageiq-automate/tests/test.yml
  content/ansible/roles/manageiq-core.manageiq-automate/vars/main.yml
  content/ansible/roles/manageiq-core.manageiq-vmdb/LICENSE
  content/ansible/roles/manageiq-core.manageiq-vmdb/README.md
  content/ansible/roles/manageiq-core.manageiq-vmdb/action_plugins/manageiq_vmdb.py
  content/ansible/roles/manageiq-core.manageiq-vmdb/defaults/main.yml
  content/ansible/roles/manageiq-core.manageiq-vmdb/handlers/main.yml
  content/ansible/roles/manageiq-core.manageiq-vmdb/library/manageiq_vmdb.py
  content/ansible/roles/manageiq-core.manageiq-vmdb/meta/main.yml
  content/ansible/roles/manageiq-core.manageiq-vmdb/tasks/main.yml
  content/ansible/roles/manageiq-core.manageiq-vmdb/tests/inventory
  content/ansible/roles/manageiq-core.manageiq-vmdb/tests/test.yml
  content/ansible/roles/manageiq-core.manageiq-vmdb/vars/main.yml
Labels: blocker, enhancement, gaprindashvili/yes

#278 [Changelog] Update for Sprint 83
  CHANGELOG.md
Labels: documentation

#203 Calculate quota using service dialogs overrides.
  content/automate/ManageIQ/System/CommonMethods/QuotaMethods.class/__methods__/requested.rb
  spec/automation/unit/method_validation/calculate_requested_spec.rb
Labels: bug, fine/yes, services

#258 Refactoring cloud vm retirement start_retirement method
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/start_retirement_spec.rb
Labels: refactoring
