Repository ManageIQ/manageiq-content, pull requests merged in 2018-12, with the labels that each got.

#480 [Changelog] Update for Sprint 100
  CHANGELOG.md
Labels: documentation

#479 [V2V] Allow a retry to let virt-v2v start
  content/automate/ManageIQ/Transformation/Common.class/__methods__/vmchecktransformed.rb
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/vmchecktransformed_spec.rb
Labels: blocker, enhancement, hammer/yes, transformation

#483 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-7
  CHANGELOG.md
Labels: documentation

#485 Fixed spec based on new validations added to ConversionHost model
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/acquiretransformationhost_spec.rb
Labels: bug, transformation

#482 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes

#484 Bug 1628240 - Fix missing word in provisioning mail's subject and body
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestapproverapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestapproverdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisionrequestapproverpending.yaml
Labels: bug

#487 [Changelog] Update for Sprint 101
  CHANGELOG.md
Labels: documentation

#489 [HAMMER] Bump hammer travis.yml to ruby 2.4.5
  .travis.yml
Labels: dependencies
