Repository ManageIQ/manageiq-content, pull requests merged in 2018-10, with the labels that each got.

#435 Keep the encrypted value as is when creating service provision request.
  content/automate/ManageIQ/System/Request.class/__methods__/order_ansible_playbook.rb
  spec/content/automate/ManageIQ/System/Request.class/__methods__/order_ansible_playbook_spec.rb
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#439 Fix userid in transformation throttler launch
  content/automate/ManageIQ/Transformation/TransformationThrottler.class/__methods__/utils.rb
  spec/content/automate/ManageIQ/Transformation/TransformationThrottler.class/__methods__/utils_spec.rb
Labels: bug, hammer/yes, transformation

#438 [HAMMER] Update i18n catalog for hammer
  locale/ManageIQ_Content.pot
  locale/en/ManageIQ_Content.po
  locale/es/ManageIQ_Content.po
  locale/fr/ManageIQ_Content.po
  locale/ja/ManageIQ_Content.po
  locale/pt_BR/ManageIQ_Content.po
  locale/zanata.xml
  locale/zh_CN/ManageIQ_Content.po
Labels: internationalization

#442 [Changelog] Update for Sprint 96
  CHANGELOG.md
Labels: documentation

#446 Modified Log_Object method to check if object is taggable.
  content/automate/ManageIQ/System/CommonMethods/Utils.class/__methods__/log_object.rb
Labels: bug, hammer/yes

#447 [HAMMER] [Changelog] Add updates for beta1.1
  CHANGELOG.md
Labels: documentation

#448 Adjust Travis postgresql from 9.4 to 9.5.
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes, test

#444 Adding better information about Quota in Used method.
  content/automate/ManageIQ/System/CommonMethods/QuotaMethods.class/__methods__/used.rb
Labels: enhancement

#451 Fix travis failure.
  spec/content/automate/ManageIQ/AutomationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/provision_spec.rb
Labels: test

#452 [Changelog] Add Sprint 97 and Hammer Beta1 updates
  CHANGELOG.md
Labels: documentation

#454 Add manageiq automate changes
  content/ansible/roles/manageiq-core.manageiq-automate/library/manageiq_automate.py
Labels: bug, gaprindashvili/yes, hammer/yes

#453 [HAMMER] [Changelog] Update for Hammer Beta2
  CHANGELOG.md
Labels: documentation
