Repository ManageIQ/manageiq-content, pull requests merged in 2018-06, with the labels that each got.

#318 [Changelog] Update for Gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#308 Email instances for /Infrastructure/Configured_System provisioning.
  content/automate/ManageIQ/Infrastructure/Configured_System/Provisioning/StateMachines/Provision.class/__class__.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructureconfiguredsystemmiqprovisioncomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructureconfiguredsystemmiqprovisionrequestapproverapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructureconfiguredsystemmiqprovisionrequestapproverdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructureconfiguredsystemmiqprovisionrequestapproverpending.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructureconfiguredsystemmiqprovisionrequestrequesterapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructureconfiguredsystemmiqprovisionrequestrequesterdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructureconfiguredsystemmiqprovisionrequestrequesterpending.yaml
  content/automate/ManageIQ/System/Policy.class/miqprovisionconfiguredsystemrequest_approved.yaml
  content/automate/ManageIQ/System/Policy.class/miqprovisionconfiguredsystemrequest_denied.yaml
  content/automate/ManageIQ/System/Policy.class/miqprovisionconfiguredsystemrequest_pending.yaml
Labels: enhancement

#309 Email instances for Host provisioning.
  content/automate/ManageIQ/Infrastructure/Host/Provisioning/StateMachines/HostProvision.class/__class__.yaml
  content/automate/ManageIQ/System/Notification/Email.class/miqhostprovisioncomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/miqhostprovisionrequestapproved.yaml
  content/automate/ManageIQ/System/Policy.class/miqhostprovisionrequest_approved.yaml
Labels: enhancement

#310 Email instances for Automation/Management/AnsibleTower provisioning.
  content/automate/ManageIQ/AutomationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__class__.yaml
  content/automate/ManageIQ/System/Notification/Email.class/automationmanagementansibletowerserviceprovisioncomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/automationmanagementansibletowerservicetemplateprovisionrequestapproverapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/automationmanagementansibletowerservicetemplateprovisionrequestrequesterapproved.yaml
Labels: enhancement

#313 Email instances for Service provisioning.
  content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/provision.yaml
  content/automate/ManageIQ/Service/Provisioning/StateMachines/ServiceProvision_Template.class/__class__.yaml
  content/automate/ManageIQ/System/Notification/Email.class/servicegenericlifecycleprovisioncomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/serviceprovisioncomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/servicetemplateprovisionrequestapproverapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/servicetemplateprovisionrequestapproverdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/servicetemplateprovisionrequestapproverpending.yaml
  content/automate/ManageIQ/System/Notification/Email.class/servicetemplateprovisionrequestrequesterapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/servicetemplateprovisionrequestrequesterdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/servicetemplateprovisionrequestrequesterpending.yaml
  content/automate/ManageIQ/System/Policy.class/servicetemplateprovisionrequest_approved.yaml
  content/automate/ManageIQ/System/Policy.class/servicetemplateprovisionrequest_denied.yaml
  content/automate/ManageIQ/System/Policy.class/servicetemplateprovisionrequest_pending.yaml
Labels: enhancement

#314 Email instances for Cloud/Orchestration.
  content/automate/ManageIQ/Cloud/Orchestration/Provisioning/StateMachines/Provision.class/__class__.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudorchestrationserviceprovisioncomplete.yaml
Labels: enhancement

#259 Refactoring cloud vm retirement pre_retirement method
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/pre_retirement.rb
  spec/automation/unit/method_validation/pre_retirement_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/pre_retirement_spec.rb
Labels: refactoring

#317 Refactoring cloud vm retirement finish_retirement method
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/finish_retirement.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/finish_retirement_spec.rb
Labels: refactoring

#319 Refactoring cloud vm retirement delete_from_vmdb method
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/delete_from_vmdb.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/delete_from_vmdb_spec.rb
Labels: refactoring

#311 Email instances for VmMigrate and Reconfiguration.
  content/automate/ManageIQ/Cloud/Orchestration/Reconfiguration/StateMachines/Reconfigure.class/__class__.yaml
  content/automate/ManageIQ/Infrastructure/VM/Migrate/StateMachines/VMMigrate.class/__class__.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudorchestrationservicereconfigureapproverapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudorchestrationservicereconfigurecomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudorchestrationservicereconfigurerequesterapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/vmmigraterequestapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/vmmigratetaskcomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/vmreconfigurerequestapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/vmreconfiguretaskcomplete.yaml
  content/automate/ManageIQ/System/Policy.class/vmmigraterequest_approved.yaml
  content/automate/ManageIQ/System/Policy.class/vmreconfigurerequest_approved.yaml
Labels: enhancement

#323 [Changelog] Update for Sprint 87
  CHANGELOG.md
Labels: documentation

#285 handle volume snapshot status changes
  content/automate/ManageIQ/System/Event/EmsEvent/Amazon.class/ebs_snapshot_notification.yaml
Labels: bug

#324 Tag migrated VM.
  content/automate/ManageIQ/Transformation/Infrastructure/VM/vmwarews.class/__methods__/setmigrated.rb
Labels: enhancement, gaprindashvili/yes, transformation

#327 Set insecure_connection to target provider as default behavior.
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/vmtransform_vmwarews2rhevm_vddk.rb
Labels: bug, gaprindashvili/yes, transformation

#320 Refactoring cloud vm retirement check_removed_from_provider method
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/check_removed_from_provider.rb
  spec/automation/unit/method_validation/check_removed_from_provider_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/check_removed_from_provider_spec.rb
Labels: refactoring

#257 Refactoring cloud vm retirement remove_from_provider method
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/remove_from_provider.rb
  spec/automation/unit/method_validation/remove_from_provider_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/remove_from_provider_spec.rb
Labels: refactoring

#331 Remove check for a state of initialized in 4 start_retirement methods.
  content/automate/ManageIQ/Cloud/Orchestration/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  spec/automation/unit/method_validation/orchestration_retirement_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/start_retirement_spec.rb
Labels: bug

#321 Refactoring cloud vm retirement check_deleted_from_provider method
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/check_deleted_from_provider.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/check_deleted_from_provider_spec.rb
Labels: refactoring

#326 Refactoring cloud vm retirement amazon_pre_retirement method
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/amazon_pre_retirement.rb
  spec/automation/unit/method_validation/amazon_pre_retirement_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/amazon_pre_retirement_spec.rb
Labels: refactoring

#329 Raise policy event when HOST_FAILURE is received.
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/host_failure.yaml
Labels: enhancement, gaprindashvili/no

#337 [Changelog] Update for Sprint 88
  CHANGELOG.md
Labels: documentation

#338 Add extra empty states to allow pre and post states.
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/__class__.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformation.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/vmwarews2rhevm_vddk.yaml
Labels: enhancement, transformation

#340 Add a state to restore VM attributes during migration.
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/restorevmattributes.rb
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/restorevmattributes.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformation.yaml
Labels: blocker, enhancement, gaprindashvili/yes, transformation

#339 Add a precanned physical server automation event
  content/automate/ManageIQ/System/Event/EmsEvent/LenovoXclarity.class/serverpoweredoffevent.yaml
Labels: enhancement, events, providers/physical

#344 Deprecate old Cloud Orchestration Reconfiguration email methods
  content/automate/ManageIQ/Cloud/Orchestration/Reconfiguration/Email.class/__methods__/servicereconfigure_complete.rb
  content/automate/ManageIQ/Cloud/Orchestration/Reconfiguration/Email.class/__methods__/servicereconfigurerequest_approved.rb
Labels: technical debt
