Repository ManageIQ/manageiq-content, pull requests merged in 2019-02, with the labels that each got.

#506 Add specs for storage_hosts that are inaccessible
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/vmware_best_fit_least_utilized_spec.rb
Labels: bug, hammer/no

#507 Update specs for ConversionHost validation changes.
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/acquiretransformationhost_spec.rb
  spec/content/automate/ManageIQ/Transformation/TransformationThrottler.class/__methods__/utils_spec.rb
Labels: test

#508 [Changelog] Update for Sprint 105
  CHANGELOG.md
Labels: documentation

#510 [Changelog] Update for Hammer-3
  CHANGELOG.md
Labels: documentation, hammer/yes
