Repository ManageIQ/manageiq-content, pull requests merged in 2019-05, with the labels that each got.

#532 VM Retirement Request - clear values from vmretire_request_starting instance.
  content/automate/ManageIQ/System/Policy.class/vmretirerequest_starting.yaml
Labels: bug, hammer/yes

#529 Create Publish to Template email instance and method.
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/VMProvision_Template.class/__class__.yaml
  content/automate/ManageIQ/System/Notification/Email.class/__methods__/miq_provision_template_customize_body.rb
  content/automate/ManageIQ/System/Notification/Email.class/__methods__/miq_provision_template_customize_body.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructuremiqprovisiontemplatecomplete.yaml
  spec/content/automate/ManageIQ/System/Notification/Email.class/__methods__/miq_provision_template_customize_body_spec.rb
Labels: bug, hammer/yes

#533 Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#536 [Changelog] Update for Hammer-6
  CHANGELOG.md
Labels: documentation, hammer/yes

#528 Launch ansible job with a specified zone.
  content/automate/ManageIQ/AutomationManagement/AnsibleTower/Operations/StateMachines/Job.class/__methods__/launch_ansible_job.rb
  spec/content/automate/ManageIQ/AutomationManagement/AnsibleTower/Operations/StateMachines/Job.class/__methods__/launch_ansible_job_spec.rb
Labels: changelog/yes, enhancement, hammer/no

#535 Support flavors for catalog bundles with Orchestration
  content/automate/ManageIQ/Cloud/Orchestration/Operations/Methods.class/__methods__/available_flavors.rb
  spec/content/automate/ManageIQ/Cloud/Orchestration/Operations/Methods.class/__methods__/available_flavors_spec.rb
Labels: bug, providers/cloud

#531 Change refresh target to src_vm_or_dest_host for DrsMigrateVM_Task_Complete
  content/automate/ManageIQ/System/Event/EmsEvent/EVM.class/drsmigratevm_task_complete.yaml
Labels: bug, changelog/yes, hammer/yes

#524 Removing dependecy on the spec helper file from the main repo
  .rspec
  .rspec_ci
  spec/spec_helper.rb
Labels: changelog/no, technical debt

#530 Fix Service Retirement requests leaving the Service as 'retiring'.
  content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirement.class/__methods__/update_service_retirement_status.rb
  spec/content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirement.class/__methods__/update_service_retirement_status_spec.rb
Labels: bug
