Repository ManageIQ/manageiq-content, pull requests merged in 2019-11, with the labels that each got.

#595 Sprint 122 and 123
  CHANGELOG.md
Labels: documentation

#589 Refactor AE Content Task Finished method and add spec
  content/automate/ManageIQ/System/CommonMethods/StateMachineMethods.class/__methods__/task_finished.rb
  spec/content/automate/ManageIQ/System/CommonMethods/StateMachineMethods.class/__methods__/task_finished_spec.rb
Labels: refactoring

#608 Optionally symlink spec/manageiq during bin/setup
  bin/setup
Labels: changelog/yes, enhancement, test

#592 Removing 6 old unused specs.
  spec/automation/unit/method_validation/amazon_auto_placement_spec.rb
  spec/automation/unit/method_validation/azure_auto_placement_spec.rb
  spec/automation/unit/method_validation/google_auto_placement_spec.rb
  spec/automation/unit/method_validation/vm_migrate_task_complete_spec.rb
  spec/automation/unit/method_validation/vm_reconfigure_request_approved_spec.rb
  spec/automation/unit/method_validation/vm_reconfigure_task_complete_spec.rb
Labels: cleanup, test

#606 Refactor AE Content Rejected method and add spec
  content/automate/ManageIQ/System/CommonMethods/QuotaStateMachine.class/__methods__/rejected.rb
  spec/content/automate/ManageIQ/System/CommonMethods/QuotaStateMachine.class/__methods__/rejected_spec.rb
Labels: refactoring

#607 Refactor approve_request method for Infra VM Retirement Approval.
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/approve_request.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/RetirementRequestApproval.class/__methods__/approve_request_spec.rb
Labels: refactoring

#605 Added test for remove_from_provider method for Cloud Vm Retirement.
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/remove_from_provider_spec.rb
Labels: test

#603 Refactor delete_service_from_vmdb method for Service Retirement.
  content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/delete_service_from_vmdb.rb
  spec/content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/delete_service_from_vmdb_spec.rb
Labels: refactoring

#599 Refactor finish_retirement method for Infra VM Retirement.
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/finish_retirement.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/finish_retirement_spec.rb
Labels: refactoring

#598 Refactor remove_from_provider method for Infra VM Retirement.
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/remove_from_provider.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/remove_from_provider_spec.rb
Labels: refactoring

#597 Refactor delete_from_vmdb method for Infra VM Retirement.
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/delete_from_vmdb.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/delete_from_vmdb_spec.rb
Labels: refactoring

#596 Refactor check_pre_retirement for Cloud Vm Retirement.
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/check_pre_retirement.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/check_pre_retirement_spec.rb
Labels: refactoring

#593 Removing power_off and check_power_off methods in Retirement class.
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/check_powered_off.rb
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/check_powered_off.yaml
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/power_off.rb
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/power_off.yaml
  spec/automation/unit/method_validation/power_off_spec.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/check_powered_off_spec.rb
Labels: cleanup, test

#609 Refactor approve_request method for Service Retirement Approval.
  content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirementRequestApproval.class/__methods__/approve_request.rb
  spec/content/automate/ManageIQ/Service/Retirement/StateMachines/ServiceRetirementRequestApproval.class/__methods__/approve_request_spec.rb
Labels: refactoring

#600 Refactor start_retirement method for Infra VM Retirement.
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/start_retirement_spec.rb
Labels: refactoring

#601 Refactor start_retirement method for Service Retirement.
  content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  spec/content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/start_retirement_spec.rb
Labels: refactoring

#602 Refactor finish_retirement method for Service Retirement.
  content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/finish_retirement.rb
  spec/content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/finish_retirement_spec.rb
Labels: refactoring
