Repository ManageIQ/manageiq-content, pull requests merged in 2019-06, with the labels that each got.

#539 [Changelog] Update for Sprint 112
  CHANGELOG.md
Labels: documentation

#542 [Changelog] Update for Hammer-7
  CHANGELOG.md
Labels: documentation, hammer/yes

#543 Fix v2v specs after cluster validation changes.
  spec/content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/checkvmininventory_spec.rb
Labels: test

#541 Support handling of special passwords like provision dialogs
  content/automate/ManageIQ/Service/Provisioning/StateMachines/Methods.class/__methods__/dialog_parser.rb
  spec/automation/unit/method_validation/dialog_parser_spec.rb
Labels: enhancement, providers/provisioning
