Repository ManageIQ/manageiq-content, pull requests merged in 2019-03, with the labels that each got.

#504 v2v Throttling moved to backend
  content/automate/ManageIQ/Transformation/Common.class/__methods__/acquiretransformationhost.yaml
  content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformation.rb
  content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformation.yaml
  content/automate/ManageIQ/Transformation/Common.class/__methods__/preflightcheck.rb
  content/automate/ManageIQ/Transformation/Common.class/__methods__/preflightcheck.yaml
  content/automate/ManageIQ/Transformation/Common.class/__methods__/vmchecktransformed.rb
  content/automate/ManageIQ/Transformation/StateMachines/TransformationThrottler.class/__class__.yaml
  content/automate/ManageIQ/Transformation/StateMachines/TransformationThrottler.class/default.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/posttransform.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/pretransform.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transform.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformation.yaml
  content/automate/ManageIQ/Transformation/TransformationThrottler.class/__class__.yaml
  content/automate/ManageIQ/Transformation/TransformationThrottler.class/__methods__/throttle.rb
  content/automate/ManageIQ/Transformation/TransformationThrottler.class/__methods__/utils.rb
  content/automate/ManageIQ/Transformation/TransformationThrottler.class/__methods__/utils.yaml
  content/automate/ManageIQ/Transformation/TransformationThrottler.class/__methods__/watch.rb
  content/automate/ManageIQ/Transformation/TransformationThrottler.class/__methods__/watch.yaml
  content/automate/ManageIQ/Transformation/TransformationThrottler.class/_missing.yaml
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/assesstransformation_spec.rb
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/preflightcheck_spec.rb
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/vmchecktransformed_spec.rb
  spec/content/automate/ManageIQ/Transformation/TransformationThrottler.class/__methods__/utils_spec.rb
Labels: enhancement, hammer/yes, transformation

#511 Remove openshift deployment
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__class__.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/add_provider.rb
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/add_provider.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/analyze_deployment.rb
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/analyze_deployment.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/check_ssh.rb
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/check_ssh.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/cleanup.rb
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/cleanup.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/deployment.rb
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/deployment.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/post_provision.rb
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/post_provision.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/pre_deployment.rb
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/pre_deployment.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/pre_validate.rb
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/pre_validate.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/provision.rb
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/__methods__/provision.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/Deployment.class/deployment.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/System/StateMachine/__namespace__.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/System/__namespace__.yaml
  content/automate/ManageIQ/Deployment/ContainerProvider/__namespace__.yaml
  content/automate/ManageIQ/Deployment/__namespace__.yaml
Labels: hammer/no, technical debt

#509 [V2V] Remove SetDescription state
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/setdescription.rb
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/setdescription.yaml
  content/automate/ManageIQ/Transformation/Infrastructure/VM/rhevm.class/__class__.yaml
  content/automate/ManageIQ/Transformation/Infrastructure/VM/rhevm.class/__methods__/utils.rb
  content/automate/ManageIQ/Transformation/Infrastructure/VM/rhevm.class/__methods__/utils.yaml
  content/automate/ManageIQ/Transformation/Infrastructure/VM/rhevm.class/_missing.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/posttransform.yaml
Labels: bug, hammer/yes, transformation

#512 [Changelog] Update for Sprint 106
  CHANGELOG.md
Labels: documentation

#513 [V2V] Remove check on power_off variable
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/poweroff.rb
Labels: blocker, bug, hammer/yes, transformation

#517 [Changelog] Update for Sprint 107
  CHANGELOG.md
Labels: documentation

#514 [V2V] Expose virt-v2v-wrapper error message in progress.states
  content/automate/ManageIQ/Transformation/Common.class/__methods__/vmchecktransformed.rb
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/vmchecktransformed_spec.rb
Labels: enhancement, hammer/yes, transformation

#519 Update supported ruby versions on Travis
  .travis.yml
Labels: test

#520 [Changelog] Update for Hammer-4
  CHANGELOG.md
Labels: documentation, hammer/yes

#515 Fixed State Machine and Instances for Vm Retirement.
  content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/VMRetirement.class/__class__.yaml
  content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/VMRetirement.class/__class__.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudvmretired.yaml
  content/automate/ManageIQ/System/Notification/Email.class/infrastructurevmretired.yaml
Labels: bug
