Repository ManageIQ/manageiq-content, pull requests merged in 2019-09, with the labels that each got.

#568 [V2V] Remove PowerOff state
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/poweroff.rb
  content/automate/ManageIQ/Transformation/Infrastructure/VM/Common.class/__methods__/poweroff.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/pretransform.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformation.yaml
Labels: ivanchuk/yes, refactoring, transformation

#571 Allow for nulls in the exists method
  content/ansible/roles/manageiq-core.manageiq-automate/library/manageiq_automate.py
Labels: bug

#577 [Changelog] Update for Ivanchuk-1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#574 [V2V] Remove TransformationHost code
  content/automate/ManageIQ/System/Request.class/transformation_transformationhostrole_check.yaml
  content/automate/ManageIQ/System/Request.class/transformation_transformationhostrole_disable.yaml
  content/automate/ManageIQ/System/Request.class/transformation_transformationhostrole_enable.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/StateMachines/TransformationHostRole.class/__class__.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/StateMachines/TransformationHostRole.class/__methods__/update_status.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/StateMachines/TransformationHostRole.class/__methods__/update_status.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/StateMachines/TransformationHostRole.class/check.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/StateMachines/TransformationHostRole.class/disable.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/StateMachines/TransformationHostRole.class/enable.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/StateMachines/__namespace__.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/__namespace__.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__class__.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/rolecheck.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/rolecheck.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/roledisable.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/roledisable.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/roleenable.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/roleenable.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/tagasdisabled.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/tagasdisabled.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/tagasenabled.rb
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/__methods__/tagasenabled.yaml
  content/automate/ManageIQ/Transformation/TransformationHosts/ovirt_host.class/_missing.yaml
Labels: ivanchuk/yes, refactoring, transformation

#580 update_attributes was replaced by update
  spec/automation/unit/method_validation/azure_pre_retirement_spec.rb
  spec/automation/unit/method_validation/check_openstack_pre_retirement_spec.rb
  spec/automation/unit/method_validation/check_unregistered_from_provider_spec.rb
  spec/automation/unit/method_validation/orchestration_retirement_spec.rb
  spec/automation/unit/method_validation/requested_spec.rb
  spec/automation/unit/method_validation/scvmm_microsoft_best_fit_least_utilized_spec.rb
  spec/content/automate/ManageIQ/Cloud/Orchestration/Provisioning/StateMachines/Methods.class/__methods__/check_provisioned_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Provisioning/Naming.class/__methods__/vmname_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/Email.class/__methods__/vm_retire_extend_spec.rb
  spec/content/automate/ManageIQ/Cloud/VM/Retirement/StateMachines/Methods.class/__methods__/pre_retirement_spec.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Migrate/StateMachines/Methods.class/__methods__/checkmigration_spec.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/Naming.class/__methods__/vmname_spec.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/vmware_best_fit_least_utilized_spec.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Retirement/Email.class/__methods__/vm_retire_extend_spec.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/check_powered_off_spec.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Retirement/StateMachines/Methods.class/__methods__/check_pre_retirement_spec.rb
  spec/content/automate/ManageIQ/System/Event/StateMachines/Refresh.class/__methods__/check_refreshed_spec.rb
  spec/content/automate/ManageIQ/System/Notification/Email.class/__methods__/miq_provision_customize_body_spec.rb
  spec/content/automate/ManageIQ/System/Notification/Email.class/__methods__/miq_provision_template_customize_body_spec.rb
  spec/content/automate/ManageIQ/System/Request.class/__methods__/vm_retire_extend_spec.rb
Labels: changelog/yes, ivanchuk/no, technical debt

#579 [V2V] Remove SetMigrated state. Cleanup state machine.
  content/automate/ManageIQ/Transformation/Common.class/__methods__/killvirtv2v.rb
  content/automate/ManageIQ/Transformation/Common.class/__methods__/killvirtv2v.yaml
  content/automate/ManageIQ/Transformation/Common.class/__methods__/setmigrated.rb
  content/automate/ManageIQ/Transformation/Common.class/__methods__/setmigrated.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/posttransform.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformation.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformationcleanup.yaml
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/killvirtv2v_spec.rb
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/setmigrated_spec.rb
Labels: ivanchuk/yes, refactoring, transformation

#582 Add handling vnic events for rhev
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/add_vnic_profile.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/network_add_network.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/network_update_network.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/remove_vnic_profile.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/update_vnic_profile.yaml
Labels: enhancement, events, ivanchuk/yes, providers/virtual

#583 [Changelog] Update for Sprint 120
  CHANGELOG.md
Labels: documentation
