Repository ManageIQ/manageiq-content, pull requests merged in 2019-01, with the labels that each got.

#491 #raw_stdout does not exist for workflow template job.
  content/automate/ManageIQ/AutomationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/check_provisioned.rb
  content/automate/ManageIQ/AutomationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/post_provision.rb
  spec/content/automate/ManageIQ/AutomationManagement/AnsibleTower/Service/Provisioning/StateMachines/Provision.class/__methods__/check_provisioned_spec.rb
Labels: blocker, bug, hammer/yes

#493 When all child retirement tasks are finished, service retirement is done.
  content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/check_service_retired.rb
  spec/content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/check_service_retired_spec.rb
Labels: blocker, bug, hammer/yes

#494 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation

#496 [Changelog] Update for Sprint 102
  CHANGELOG.md
Labels: documentation

#497 Add handler for compute.instance.update
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/compute.instance.update.yaml
Labels: enhancement, events, hammer/yes, providers/cloud

#501 Fixes Error during substitution for Service Provisioning Email.
  content/automate/ManageIQ/System/Notification/Email.class/serviceprovisioncomplete.yaml
Labels: bug, hammer/yes

#502 [Changelog] Update for Sprint 103
  CHANGELOG.md
Labels: documentation

#503 fixing travis: do not create Tag explicitly
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/Naming.class/__methods__/vmname_spec.rb
Labels: bug, test

#505 [Changelog] Update for Hammer-2
  CHANGELOG.md
Labels: documentation, hammer/yes
