Repository ManageIQ/manageiq-content, pull requests merged in 2019-10, with the labels that each got.

#585 [HAMMER] Add retry_interval to VMCheckTransformed
  content/automate/ManageIQ/Transformation/Common.class/__methods__/vmchecktransformed.rb
Labels: bug, hammer/yes, transformation

#584 Switch to call lookup_by_* methods
  content/automate/ManageIQ/Infrastructure/VM/Transform/Import.class/__methods__/list_tag_names.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Transform/Import.class/__methods__/list_tag_names_spec.rb
Labels: changelog/yes, ivanchuk/no, refactoring

#578 Eligible storages for placement methods
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/microsoft_best_fit_least_utilized.rb
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/vmware_best_fit_least_utilized.rb
  spec/automation/unit/method_validation/scvmm_microsoft_best_fit_least_utilized_spec.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/vmware_best_fit_least_utilized_spec.rb
Labels: changelog/yes, enhancement, providers/provisioning, providers/virtual

#588 AzureStack events for targeted refresh
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/__class__.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/_missing.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.compute_virtualmachines_deallocate_succeeded.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.compute_virtualmachines_delete_succeeded.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.compute_virtualmachines_restart_succeeded.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.compute_virtualmachines_start_succeeded.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.compute_virtualmachines_write_succeeded.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.network_networkinterfaces_delete_succeeded.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.network_networkinterfaces_write_succeeded.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.network_networksecuritygroups_delete_succeeded.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.network_networksecuritygroups_write_succeeded.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.network_virtualnetworks_delete_succeeded.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.network_virtualnetworks_subnets_delete_succeeded.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.network_virtualnetworks_subnets_write_succeeded.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/AzureStack.class/administrative_microsoft.network_virtualnetworks_write_succeeded.yaml
Labels: changelog/yes, enhancement, events, ivanchuk/no, providers/cloud

#587 Refactor Quota Source method and spec
  content/automate/ManageIQ/System/CommonMethods/QuotaMethods.class/__methods__/quota_source.rb
  spec/content/automate/ManageIQ/System/CommonMethods/QuotaMethods.class/__methods__/quota_source_spec.rb
Labels: refactoring

#590 Remove call to retire_service_resources from retire_service method
  content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/retire_service.rb
Labels: changelog/yes, cleanup, ivanchuk/no

#591 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
Labels: changelog/yes, dependencies, test

#594 Cleanup after Ansible runner integration
  content/automate/ManageIQ/AutomationManagement/AnsibleTower/Operations/Methods.class/__methods__/available_credentials.rb
  spec/content/automate/ManageIQ/AutomationManagement/AnsibleTower/Operations/Methods.class/__methods__/available_credentials_spec.rb
Labels: changelog/yes, embedded ansible, hammer/no, ivanchuk/yes, refactoring, services
