Repository ManageIQ/manageiq-content, pull requests merged in 2019-04, with the labels that each got.

#522 Update .travis.yml PostgreSQL version to 10
  .travis.yml
Labels: enhancement

#518 Fixed State machine for Cloud Orchestration Retirement using old values.
  content/automate/ManageIQ/Cloud/Orchestration/Retirement/StateMachines/StackRetirement.class/__class__.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudorchestrationvmretired.yaml
Labels: bug

#525 Use the Ems last_inventory_date for ReconfigVM
  content/automate/ManageIQ/System/Event/StateMachines/Refresh.class/__methods__/check_refreshed.rb
  content/automate/ManageIQ/System/Event/StateMachines/Refresh.class/__methods__/target_refresh.rb
  spec/content/automate/ManageIQ/System/Event/StateMachines/Refresh.class/__methods__/check_refreshed_spec.rb
  spec/content/automate/ManageIQ/System/Event/StateMachines/Refresh.class/__methods__/target_refresh_spec.rb
Labels: enhancement

#526 [Changelog] Update for Hammer-5 release
  CHANGELOG.md
Labels: documentation, hammer/yes

#527 Fix call to time method for miq_provision_customize_body.
  content/automate/ManageIQ/System/Notification/Email.class/__methods__/miq_provision_customize_body.rb
Labels: bug, hammer/yes

#490 Changes to launch_ansible_job to support Ansible Tower workflow template.
  content/automate/ManageIQ/AutomationManagement/AnsibleTower/Operations/StateMachines/Job.class/__methods__/launch_ansible_job.rb
  content/automate/ManageIQ/AutomationManagement/AnsibleTower/Operations/StateMachines/Job.class/__methods__/wait_for_completion.rb
  spec/content/automate/ManageIQ/AutomationManagement/AnsibleTower/Operations/StateMachines/Job.class/__methods__/launch_ansible_job_spec.rb
Labels: bug, hammer/yes

#516 Introduce PhysicalServerProvision StateMachine
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Lifecycle.class/__class__.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Lifecycle.class/provisioning.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/Profile.class/__class__.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/Profile.class/_missing.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/Profile.class/evmgroup-super_administrator.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Methods.class/__class__.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Methods.class/__methods__/check_provision.rb
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Methods.class/__methods__/check_provision.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Methods.class/__methods__/provision.rb
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Methods.class/__methods__/provision.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Methods.class/checkprovision.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Methods.class/postprovision.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Methods.class/preprovision.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Methods.class/provision.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Provision.class/__class__.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Provision.class/__methods__/update_provision_status.rb
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Provision.class/__methods__/update_provision_status.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Provision.class/default.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/__namespace__.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/__namespace__.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/__namespace__.yaml
  content/automate/ManageIQ/PhysicalInfrastructure/__namespace__.yaml
  spec/content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Methods.class/__methods__/check_provision_spec.rb
  spec/content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Methods.class/__methods__/provision_spec.rb
  spec/content/automate/ManageIQ/PhysicalInfrastructure/PhysicalServer/Provisioning/StateMachines/Provision.class/__methods__/update_provision_status_spec.rb
Labels: enhancement, providers/physical, wip
