Repository ManageIQ/manageiq-content, pull requests merged in 2019-12, with the labels that each got.

#612 Add OpenStack SecurityGroupRule Events
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/security_group_rule.create.end.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/security_group_rule.delete.end.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/security_group_rule.update.end.yaml
Labels: enhancement, events, providers/cloud

#614 Fix broken spec.
  spec/content/automate/ManageIQ/Infrastructure/VM/Transform/Import.class/__methods__/list_storages_spec.rb
Labels: test

#613 [IVANCHUK] Ivanchuk-2 Changelog
  CHANGELOG.md
  Extensions/WalkmeExtension@walkme.com.xpi
Labels: documentation

#611 Save automate timeout value for service.execute step into service's options hash
  content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/execute.rb
  spec/content/automate/ManageIQ/Service/Generic/StateMachines/GenericLifecycle.class/__methods__/execute_spec.rb
Labels: changelog/yes, enhancement, services

#616 [Changelog] Update for Sprints 124 and 125
  CHANGELOG.md
Labels: documentation

#617 Initial CODEOWNERS checkin
  .github/CODEOWNERS
Labels: changelog/no, documentation

#619 Adding better logging to check_service_retire method.
  content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/check_service_retired.rb
Labels: enhancement
