Repository ManageIQ/manageiq-content, pull requests merged in 2019-07, with the labels that each got.

#549 Add a rubocop channel to the codeclimate config
  .codeclimate.yml
Labels: bug, dependencies, test

#550 [Changelog] Update for Hammer-9
  CHANGELOG.md
Labels: documentation, hammer/yes

#554 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes
