Repository ManageIQ/manageiq-content, pull requests merged in 2020-01, with the labels that each got.

#621 Added test for check_service_retired method for Service Retirement.
  spec/content/automate/ManageIQ/Service/Retirement/StateMachines/Methods.class/__methods__/check_service_retired_spec.rb
Labels: test

#620 Fix for Quota validation issue with service dialog memory values.
  content/automate/ManageIQ/System/CommonMethods/QuotaMethods.class/__methods__/requested.rb
  spec/automation/unit/method_validation/requested_spec.rb
Labels: bug, changelog/yes, hammer/no, ivanchuk/no

#625 Add an automate event for DrsMigrateVM_Task
  content/automate/ManageIQ/System/Event/EmsEvent/VC.class/drsmigratevm_task.yaml
Labels: changelog/yes, enhancement, events, ivanchuk/yes, providers/virtual

#631 Add Sprint 127 Change detail.
  CHANGELOG.md
Labels: changelog/no, documentation

#629 Refactor redhat_best_fit_cluster method for VM Placement.
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/redhat_best_fit_cluster.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/redhat_best_fit_cluster_spec.rb
Labels: changelog/yes, ivanchuk/no, refactoring

#626 Refactor microsoft_best_fit_least_utilized method for VM Placement.
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/microsoft_best_fit_least_utilized.rb
  spec/automation/unit/method_validation/scvmm_microsoft_best_fit_least_utilized_spec.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/Placement.class/__methods__/microsoft_best_fit_least_utilized_spec.rb
Labels: refactoring

#615 Refactor start_retirement method for Cloud Orchestration Retirement.
  content/automate/ManageIQ/Cloud/Orchestration/Retirement/StateMachines/Methods.class/__methods__/start_retirement.rb
  spec/automation/unit/method_validation/orchestration_retirement_spec.rb
  spec/content/automate/ManageIQ/Cloud/Orchestration/Retirement/StateMachines/Methods.class/__methods__/start_retirement_spec.rb
Labels: refactoring

#634 Fix cancellation process
  content/automate/ManageIQ/Transformation/Common.class/__methods__/waitforhandover.rb
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/waitforhandover_spec.rb
Labels: bug, changelog/yes, ivanchuk/yes, v2v

#635 [Changelog] Update for Sprint 128
  CHANGELOG.md
Labels: changelog/no, documentation
