Repository ManageIQ/manageiq-content, pull requests merged in 2020-08, with the labels that each got.

#644 Refactor vmware_preprovision method for VM Provisioning.
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/vmware_preprovision.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/vmware_preprovision_spec.rb
Labels: refactoring

#643 Refactor redhat_preprovision method for VM Provisioning.
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/redhat_preprovision.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/redhat_preprovision_spec.rb
Labels: refactoring

#666 Remove refresh_new_target in favor of manager_refresh
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/importexport_import_vm.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/importexport_starting_import_vm.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/network_add_vm_interface.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/network_interface_plugged_into_vm.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/update_vnic_profile.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/user_add_vm.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/user_add_vm_finished_success.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/user_add_vm_template.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/user_add_vm_template_finished_success.yaml
  content/automate/ManageIQ/System/Event/EmsEvent/RHEVM.class/vm_import_from_configuration_executed_successfully.yaml
  content/automate/ManageIQ/System/event_handlers.class/__methods__/event_action_refresh_new_target.yaml
  content/automate/ManageIQ/System/event_handlers.class/event_action_refresh_new_target.yaml
Labels: refactoring

#645 Refactor vmware_preprovision_clone_to_template method for VM Provisioning.
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/vmware_preprovision_clone_to_template.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/vmware_preprovision_clone_to_template_spec.rb
Labels: refactoring

#646 Refactor vmware_preprovision_clone_to_vm method for VM Provisioning.
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/vmware_preprovision_clone_to_vm.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/vmware_preprovision_clone_to_vm_spec.rb
Labels: refactoring

#659 Fix missing retry values in Service provisioning state machine class.
  content/automate/ManageIQ/Service/Provisioning/StateMachines/ServiceProvision_Template.class/__class__.yaml
Labels: bug, changelog/yes

#655 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer, documentation

#660 Delete Migration feature - Automate
  content/automate/ManageIQ/System/CommonMethods/MiqAe.class/__class__.yaml
  content/automate/ManageIQ/System/CommonMethods/MiqAe.class/__methods__/weightedupdatestatus.rb
  content/automate/ManageIQ/System/CommonMethods/MiqAe.class/__methods__/weightedupdatestatus.yaml
  content/automate/ManageIQ/System/Notification/Email.class/transformationplancomplete.yaml
  content/automate/ManageIQ/System/Notification/Email.class/transformationplanrequestapproverapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/transformationplanrequestapproverdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/transformationplanrequestapproverpending.yaml
  content/automate/ManageIQ/System/Notification/Email.class/transformationplanrequestrequesterapproved.yaml
  content/automate/ManageIQ/System/Notification/Email.class/transformationplanrequestrequesterdenied.yaml
  content/automate/ManageIQ/System/Notification/Email.class/transformationplanrequestrequesterpending.yaml
  content/automate/ManageIQ/System/Policy.class/servicetemplatetransformationplanrequest_approved.yaml
  content/automate/ManageIQ/System/Policy.class/servicetemplatetransformationplanrequest_created.yaml
  content/automate/ManageIQ/System/Policy.class/servicetemplatetransformationplanrequest_denied.yaml
  content/automate/ManageIQ/System/Policy.class/servicetemplatetransformationplanrequest_pending.yaml
  content/automate/ManageIQ/System/Policy.class/servicetemplatetransformationplanrequest_starting.yaml
  content/automate/ManageIQ/Transformation/Common.class/__class__.yaml
  content/automate/ManageIQ/Transformation/Common.class/__methods__/utils.rb
  content/automate/ManageIQ/Transformation/Common.class/__methods__/utils.yaml
  content/automate/ManageIQ/Transformation/Common.class/__methods__/waitforhandover.rb
  content/automate/ManageIQ/Transformation/Common.class/__methods__/waitforhandover.yaml
  content/automate/ManageIQ/Transformation/Common.class/_missing.yaml
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__class__.yaml
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__/approve_request.rb
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__/approve_request.yaml
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__/deny_request.rb
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__/deny_request.yaml
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__/validate_request.rb
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/__methods__/validate_request.yaml
  content/automate/ManageIQ/Transformation/StateMachines/TransformationPlanRequestApproval.class/default.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/__class__.yaml
  content/automate/ManageIQ/Transformation/StateMachines/VMTransformation.class/transformation.yaml
  content/automate/ManageIQ/Transformation/StateMachines/__namespace__.yaml
  content/automate/ManageIQ/Transformation/__namespace__.yaml
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/utils_spec.rb
  spec/content/automate/ManageIQ/Transformation/Common.class/__methods__/waitforhandover_spec.rb
Labels: technical debt
