Repository ManageIQ/manageiq-content, pull requests merged in 2020-07, with the labels that each got.

#661 Add compute.instance.resize.confirm.end to OpenStack event types
  content/automate/ManageIQ/System/Event/EmsEvent/OpenStack.class/compute.instance.resize.confirm.end.yaml
Labels: enhancement

#662 Raise error for Azure if no subnets can be found for a cloud network
  content/automate/ManageIQ/Cloud/VM/Provisioning/Placement.class/__methods__/best_fit_azure.rb
Labels: bug

#665 Add APP_PATH to allow using Rails directly
  bin/rails
Labels: developer, enhancement
