Repository ManageIQ/manageiq-content, pull requests merged in 2020-10, with the labels that each got.

#667 Plugin Generator Updates
  .codeclimate.yml
  .gitignore
  .rspec
  .rspec_ci
  .rubocop.yml
  .rubocop_cc.yml
  .travis.yml
  .yamllint
  Gemfile
  README.md
  Rakefile
  bin/ci/after_script
  bin/update
  bundler.d/.keep
  config/settings.yml
  lib/manageiq/content/engine.rb
  lib/tasks/README.md
  lib/tasks_private/spec.rake
  locale/.keep
  manageiq-content.gemspec
  spec/spec_helper.rb
  spec/support/automate_class_definition_hook.rb
  spec/support/require_domain_helper.rb
Labels: developer

#668 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: dependencies

#669 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-content.gemspec
Labels: developer, enhancement

#670 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer

#676 [JANSA] Fix whitespace for Travis
  content/automate/ManageIQ/System/About.class/__class__.yaml
Labels: bug

#677 Avoid using YAML in rake release to minimize file changes
  lib/tasks_private/release.rake
Labels: bug, jansa/yes, kasparov/yes
