Repository ManageIQ/manageiq-content, pull requests merged in 2020-03, with the labels that each got.

#647 [Changelog] Update for Sprint 131
  CHANGELOG.md
Labels: changelog/no, documentation

#649 [JANSA] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#628 Refactor amazon_customizerequest method for VM Provisioning.
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/Methods.class/__methods__/amazon_customizerequest.rb
  spec/content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/Methods.class/__methods__/amazon_customizerequest_spec.rb
Labels: refactoring

#632 Refactor openstack_customizerequest method for VM Provisioning.
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/Methods.class/__methods__/openstack_customizerequest.rb
  spec/content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/Methods.class/__methods__/openstack_customizerequest_spec.rb
Labels: refactoring

#633 Refactor redhat_customizerequest method for VM Provisioning.
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/redhat_customizerequest.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/redhat_customizerequest_spec.rb
Labels: refactoring

#638 Refactor vmware_customizerequest method for VM Provisioning.
  content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/vmware_customizerequest.rb
  spec/content/automate/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods.class/__methods__/vmware_customizerequest_spec.rb
Labels: refactoring

#650 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation
