Repository ManageIQ/manageiq-content, pull requests merged in 2022-05, with the labels that each got.

#711 Update apt-cache before running apt-get install
  bin/before_install
Labels: bug, test

#709 Add manual option for CI github workflow
  .github/workflows/ci.yaml
Labels: test

#710 Adding support for `clone_to_template` workflow to CloudManager
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/Methods.class/__class__.yaml
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/Methods.class/__methods__/ibm_powervs_preprovision_clone_to_template.rb
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/Methods.class/__methods__/ibm_powervs_preprovision_clone_to_template.yaml
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/Methods.class/preprovision.yaml
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/Methods.class/preprovision_clone_to_template.yaml
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/VMProvision_Template.class/__class__.yaml
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/VMProvision_Template.class/__methods__/update_provision_status.rb
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/VMProvision_Template.class/__methods__/update_provision_status.yaml
  content/automate/ManageIQ/Cloud/VM/Provisioning/StateMachines/VMProvision_Template.class/clone_to_template.yaml
  content/automate/ManageIQ/System/CommonMethods/StateMachineMethods.class/__methods__/task_finished.rb
  content/automate/ManageIQ/System/CommonMethods/StateMachineMethods.class/template_publish_finished.yaml
  content/automate/ManageIQ/System/Notification/Email.class/cloudmiqprovisiontemplatecomplete.yaml
  spec/content/automate/ManageIQ/System/CommonMethods/StateMachineMethods.class/__methods__/task_finished_spec.rb
Labels: enhancement
